site_name: Thohirah's Brag Documents
site_url: https://thohyr.co
theme:
  name: terminal
  palette: sans
  features:
    - revision.date
    - revision.history

nav:
  - Home: 'index.md'
  - Docs:
      - 2025: '2025.md'
      - 2024: '2024.md'
      - 2023: '2023.md'
      - 2022: '2022.md'
      - 2021: '2021.md'

markdown_extensions:
  - def_list
