[tool.poetry]
name = "brag-document"
version = "0.0.1"
description = ""
authors = ["Thoritie <thor@odds.team>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.4"
mkdocs-material = "^9.5.44"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
